services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - swiflethome-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - swiflethome-network
      
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    configs:
      - source: mosquitto_conf
        target: /mosquitto/config/mosquitto.conf
    networks:
      - swiflethome-network

configs:
  mosquitto_conf:
    content: |
      listener 1883 0.0.0.0
      allow_anonymous true
      persistence true
      persistence_location /mosquitto/data/
      log_dest stdout
      log_dest file /mosquitto/log/mosquitto.log 

networks:
  swiflethome-network:
    driver: bridge

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local