services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - swiflethome-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - swiflethome-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./tools/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - swiflethome-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./tools/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - swiflethome-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    # Jenkins cần quyền chạy yarn, build, access thư mục Mount ( Ko set mặc định dùng user 'jenkins')
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      # cho phép Jenskin trong container có thể điều kiển chính Docker chứa nó
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount thư mục nguồn với thư mục bên trong jenskin, build code và ghi đè mã nguồn được build vào thư mục nguồn
      - /var/www/SwifletHome:/var/www/SwifletHome
    networks:
      - swiflethome-network

networks:
  swiflethome-network:
    driver: bridge

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
  jenkins_data:
    driver: local
