export const Msg = {
  TokenMissing: 'Vui lòng xác thực token',
  TokenInvalid: 'Token không hợp lệ',
  PhoneExist: 'Số điện thoại đã tồn tại',
  PhoneExistForNew: 'Số điện thoại đã tồn tại cho việc đăng ký mới',
  PhoneNotExist: 'Số điện thoại không tồn tại',
  PhoneLoginWrong: 'Số điện thoại hoặc mật khẩu không hợp lệ',
  RegisterOk: 'Đăng ký tài khoản thành công',
  RegisterErr: 'Đăng ký tài khoản thất bại',
  PasswordChangeOk: 'Đổi mật khẩu thành công',
  PasswordChangeErr: 'Đổi mật khẩu thất bại',
  AccountLoginWrong: 'Tài khoản hoặc mật khẩu không hợp lệ',
  AccountLoginBlock: 'Tài khoản đã bị vô hiệu hóa',
  DataEmpty: 'Hiện tại hệ thống chưa cung cấp dữ liệu về câu hỏi/trả lời',
  CannotReply: 'Xin lỗi, tôi chưa có thông tin về câu hỏi này',
  FileEmpty: 'Không có file nào được upload',
  FileAudioRequire: 'Bắt buộc nhập 2 file audio',
  FileOvertake: 'Số file upload đã vượt quá số lượng tối đa',
  fileWrongType: (ext: string, allowedExts: string[]) => `File không hỗ trợ: ${ext}. Cho phép: ${allowedExts.join(', ')}`,
  FileDeleteFail: 'Lỗi khi xóa file',
  FileUploadFail: 'Lỗi khi xóa file',
  OtpNotVerify: 'Vui lòng xác thực OTP',
  OtpSent: 'OTP đã được gửi',
  OtpValid: 'Xác thực OTP thành công',
  OtpInvalid: 'Xác thực OTP thất bại',
  OtpExpire: 'OTP không tồn tại hoặc đã hết hạn',
  OtpOvertake: 'Đã vượt quá số lần nhập OTP cho phép',
  OtpRemainAttempt: (num) => `Mã OTP không đúng. Còn ${num} lần thử.`,
};
