export const Msg = {
  CreateOk: 'Thên thông tin thành công',
  CreateErr: 'Thêm thông tin thất bại',
  UpdateOk: 'Cập nhập thông tin thành công',
  UpdateErr: 'Cập nhập thông tin thất bại',
  CodeInvalid: 'Mã code không hợp lệ',
  TokenMissing: 'Vui lòng xác thực token',
  TokenInvalid: 'Token không hợp lệ',
  PhoneExist: 'Số điện thoại đã tồn tại',
  PhoneOk: 'Số điện thoại hợp lệ có thể thêm mới',
  PhoneExistForNew: 'Số điện thoại đã tồn tại cho việc đăng ký mới',
  PhoneNotExist: 'Số điện thoại không tồn tại',
  PhoneLoginWrong: 'Số điện thoại hoặc mật khẩu không hợp lệ',
  RegisterOk: 'Đăng ký tài khoản thành công',
  RegisterErr: 'Đăng ký tài khoản thất bại',
  PasswordChangeOk: 'Đổi mật khẩu thành công',
  PasswordChangeErr: 'Đổi mật khẩu thất bại',
  AccountLoginWrong: 'Tài khoản hoặc mật khẩu không hợp lệ',
  AccountLoginBlock: 'Tài khoản đã bị vô hiệu hóa',
  UserNotFound: 'Người dùng không tồn tại',
  HomeNotFound: 'Thông tin nhà yến không tồn tại',
  HomeSummitCreateOk: 'Đăng ký tham quan thành công',
  DoctorCreateOk: 'Gửi thông tin khám bệnh nhà yến thành công',
  CannotReply: 'Hệ thống chưa có thông tin về câu trả lời của câu hỏi này',
  uuidNotFound: 'Chưa từng có file nào được upload cùng với uuid này',
  FileEmpty: 'Không có file nào được upload',
  FileAudioRequire: 'Bắt buộc nhập 2 file audio',
  FileOvertake: 'Số file upload đã vượt quá số lượng tối đa',
  fileWrongType: (ext: string, allowedExts: string[]) => `File không hỗ trợ: ${ext}. Cho phép: ${allowedExts.join(', ')}`,
  FileDeleteFail: 'Lỗi khi xóa file',
  FileUploadFail: 'Lỗi khi xóa file',
  OtpNotVerify: 'Vui lòng xác thực OTP',
  OtpSent: 'OTP đã được gửi',
  OtpValid: 'Xác thực OTP thành công',
  OtpInvalid: 'Xác thực OTP thất bại',
  OtpExpire: 'OTP không tồn tại hoặc đã hết hạn',
  OtpOvertake: 'Đã vượt quá số lần nhập OTP cho phép',
  OtpRemainAttempt: (num) => `Mã OTP không đúng. Còn ${num} lần thử.`,
};
