export const Msg = {
  UploadOk: 'Tải ảnh lên thành công',
  UploadErr: 'Tải ảnh lên thất bại',
  GetOk: 'Lấy thông tin thành công',
  GetErr: 'Lấy thông tin thất bại',
  RegisterOk: 'Đăng ký thông tin thành công',
  RegisterErr: 'Đăng ký thông tin thất bại',
  CreateOk: 'Thêm thông tin thành công',
  CreateErr: 'Thêm thông tin thất bại',
  UpdateOk: 'Cập nhập thông tin thành công',
  UpdateErr: 'Cập nhập thông tin thất bại',
  DeleteOk: 'Xóa thông tin thành công',
  DeleteErr: 'Xóa thông tin thất bại',
  SetTaskOk:"Thiết lập lịch nhắc thành công",
  SetTaskErr:"Thiết lập lịch nhắc thất bại",
  CodeInvalid: 'Mã code không hợp lệ',
  TokenMissing: 'Vui lòng xác thực token',
  TokenInvalid: 'Token không hợp lệ',
  PhoneExist: 'Số điện thoại đã tồn tại',
  PhoneOk: 'Số điện thoại hợp lệ có thể thêm mới',
  PhoneExistForNew: 'Số điện thoại đã tồn tại cho việc đăng ký mới',
  PhoneNotExist: 'Số điện thoại không tồn tại',
  PhoneLoginWrong: 'Số điện thoại hoặc mật khẩu không hợp lệ',
  LoginOk: 'Đăng nhập thành công',
  LoginErr: 'Đăng nhập thất bại',
  RegisterAccountOk: 'Đăng ký tài khoản thành công',
  RegisterAccountErr: 'Đăng ký tài khoản thất bại',
  PasswordChangeOk: 'Đổi mật khẩu thành công',
  PasswordChangeErr: 'Đổi mật khẩu thất bại',
  AccountLoginWrong: 'Tài khoản hoặc mật khẩu không hợp lệ',
  AccountLoginBlock: 'Tài khoản đã bị vô hiệu hóa',
  UserNotFound: 'Người dùng không tồn tại',
  HomeNotFound: 'Thông tin nhà yến không tồn tại',
  HomeIsMainCannotDelete: 'Không thể xóa nhà yến đang được chọn là chính',
  CannotReply: 'Hệ thống chưa có thông tin về câu trả lời của câu hỏi này',
  UuidNotFound: 'Chưa từng có file nào được upload cùng với uuid này',
  FileEmpty: 'Không có file nào được upload',
  FileAudioRequire: 'Bắt buộc nhập 2 file audio',
  FileOvertake: 'Số file upload đã vượt quá số lượng tối đa',
  FileWrongType: (ext: string, allowedExts: string[]) => `File không hỗ trợ: ${ext}. Cho phép: ${allowedExts.join(', ')}`,
  FileDeleteFail: 'Lỗi khi xóa file',
  FileUploadFail: 'Lỗi khi xóa file',
  OtpNotVerify: 'Vui lòng xác thực OTP',
  OtpSent: 'OTP đã được gửi',
  OtpValid: 'Xác thực OTP thành công',
  OtpInvalid: 'Xác thực OTP thất bại',
  OtpExpire: 'OTP không tồn tại hoặc đã hết hạn',
  OtpOvertake: 'Đã vượt quá số lần nhập OTP cho phép',
  OtpRemainAttempt: (num: number) => `Mã OTP không đúng. Còn ${num} lần thử.`,
  InvalidPackageToAddHome: 'Vui lòng nâng cấp gói để có thể thêm nhà yến mới',
  DuplicateTaskAlram:"Lịch nhắc này đã tồn tại",
  DuplicateTaskPeriod:"Chu kỳ lịch nhắc này đã tồn tại",
  CannotNull: (filedName: string) => `${filedName} không thể trống`,
  InvalidValue: (filedName: string) => `${filedName} sai giá trị cho phép`,
  InvalidRange: (filedName: string, range: string) => `${filedName} phải nằm trong giá trị cho phép giá trị cho phép (${range})`,
  MustBeGreaterThanNow: (filedName: string) => `${filedName} phải lớn hơn ngày hiện tại`,
};
