export enum TraceabilityStatusEnum {
  PROCESSING = 'PROCESSING',
  APPROVED = 'APPROVED',
  REFUSED = 'REFUSED',
}

export enum TraceabilityActorEnum {
  HOUSE_OWNER_ACTOR = 'HOUSE_OWNER_ACTOR',
  DELIVERING_ACTOR = 'DELIVERING_ACTOR',
  PROCESSING_ACTOR = 'PROCESSING_ACTOR',
  PACKING_ACTOR = 'PACKING_ACTOR',
  DISTRIBUTION_ACTOR = 'DISTRIBUTION_ACTOR',
}
