server {
   server_name 3fam.vn www.3fam.vn;

   location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
   }

   location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        proxy_pass http://127.0.0.1:8081;
        expires 30d;
        add_header Cache_control "public, no-transform";
   }

    access_log /var/log/nginx/3fam.vn.access.log;
    error_log /var/log/nginx/3fam.vn.error.log;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/3fam.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3fam.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;


}
server {
   listen 80;
   server_name 3fam.vn www.3fam.vn;
   return 301 https://$host$request_uri;
}
